import 'package:flutter/material.dart';

/// The one colour the generated scheme does not contain: **settled green.**
///
/// Everywhere else in this app the rule holds and is worth restating — colours come out of
/// `ColorScheme`, never out of a `Color(0xff…)` at the call site, because `theme.dart` is
/// generated by the Material theme builder and gets replaced wholesale. A hex written into a
/// widget survives that replacement and quietly stops matching everything around it.
///
/// This file is the deliberate exception, and it is written as an exception rather than as a
/// habit: Material 3 ships three accents and an error, and has **no success role**. «مدفوعة
/// بالكامل» was taking `primary`, which is the same teal as «سعر الطلبية» directly beneath it and
/// as half the app besides — so the one state a person scans a list of orders *for* was drawn in
/// the colour of everything. Green says «انتهى» without being read.
///
/// Kept out of `theme.dart` on purpose: that file is regenerated, and anything added to it is
/// lost the next time somebody re-exports the palette. Kept as an extension on `ColorScheme`
/// rather than a `ThemeExtension` for the same reason — a `ThemeExtension` has to be registered
/// inside the generated `ThemeData`.
///
/// Three values, following the same tonal shape the rest of the scheme uses, so the pair reads
/// correctly in either brightness:
///
/// * [paid] — for text and outlines on a plain surface.
/// * [paidContainer] — the pale fill, «الأخضر الباهت».
/// * [onPaidContainer] — what stays readable on top of that fill.
///
/// Desaturated towards the teal it sits beside: a pure `Colors.green` next to `#006a69` reads as
/// a colour borrowed from another app.
///
/// **All three sit at 140° — green, not the 148° they started on.** That first draft was pulled
/// so far towards the teal that the chip and the price beneath it read as one decision printed
/// twice, which is the entire thing this file exists to prevent. The move is eight degrees of hue
/// and nothing else: same lightness, same saturation, so «مدفوعة بالكامل» is recognisably the
/// colour it has always been and merely stops arguing with `primary`. `app_tones_test.dart` pins
/// the band and the distance from the teal rather than these six values, so the intent survives a
/// re-export of the palette.
extension PaymentTone on ColorScheme {
  bool get _isDark => brightness == Brightness.dark;

  Color get paid => _isDark ? const Color(0xff8fd4a6) : const Color(0xff38714b);

  Color get paidContainer => _isDark ? const Color(0xff235032) : const Color(0xffc4ecd1);

  Color get onPaidContainer => _isDark ? const Color(0xffc4ecd1) : const Color(0xff235032);
}
