import 'package:flutter/material.dart';

/// The one colour the generated scheme does not contain: **settled green.**
///
/// Everywhere else in this app the rule holds and is worth restating — colours come out of
/// `ColorScheme`, never out of a `Color(0xff…)` at the call site, because `theme.dart` is
/// generated by the Material theme builder and gets replaced wholesale. A hex written into a
/// widget survives that replacement and quietly stops matching everything around it.
///
/// This file is the deliberate exception, and it is written as an exception rather than as a
/// habit: Material 3 ships three accents and an error, and has **no success role**. «مدفوعة
/// بالكامل» was taking `primary`, which is the same teal as «سعر الطلبية» directly beneath it and
/// as half the app besides — so the one state a person scans a list of orders *for* was drawn in
/// the colour of everything. Green says «انتهى» without being read.
///
/// Kept out of `theme.dart` on purpose: that file is regenerated, and anything added to it is
/// lost the next time somebody re-exports the palette. Kept as an extension on `ColorScheme`
/// rather than a `ThemeExtension` for the same reason — a `ThemeExtension` has to be registered
/// inside the generated `ThemeData`.
///
/// Three values, following the same tonal shape the rest of the scheme uses, so the pair reads
/// correctly in either brightness:
///
/// * [paid] — for text and outlines on a plain surface.
/// * [paidContainer] — the pale fill, «الأخضر الباهت».
/// * [onPaidContainer] — what stays readable on top of that fill.
///
/// Desaturated towards the teal it sits beside: a pure `Colors.green` next to `#006a69` reads as
/// a colour borrowed from another app.
///
/// **All three sit at 140° — green, not the 148° they started on.** That first draft was pulled
/// so far towards the teal that the chip and the price beneath it read as one decision printed
/// twice, which is the entire thing this file exists to prevent. The move is eight degrees of hue
/// and nothing else: same lightness, same saturation, so «مدفوعة بالكامل» is recognisably the
/// colour it has always been and merely stops arguing with `primary`. `app_tones_test.dart` pins
/// the band and the distance from the teal rather than these six values, so the intent survives a
/// re-export of the palette.
extension PaymentTone on ColorScheme {
  bool get _isDark => brightness == Brightness.dark;

  Color get paid => _isDark ? const Color(0xff8fd4a6) : const Color(0xff38714b);

  Color get paidContainer => _isDark ? const Color(0xff235032) : const Color(0xffc4ecd1);

  Color get onPaidContainer => _isDark ? const Color(0xffc4ecd1) : const Color(0xff235032);
}

/// The second thing Material 3 has no role for: **«تحت الحد» — أصفر التنبيه.**
///
/// The balances screen has three states and Material supplies two of them. «سليم» is `primary`
/// and «نافد» is `error`; «تحت الحد» was left to borrow one of the other accents, and every
/// candidate said the wrong thing — `tertiary` is a blue that reads as information, and a second
/// red would leave nothing louder for the shelf that has actually run out. A shelf that is
/// running low is neither fine nor broken, which is precisely what amber means everywhere else
/// in the world.
///
/// Added here rather than in a widget for the same reason [PaymentTone] is: `theme.dart` is
/// generated and gets replaced wholesale, and a hex written into a screen survives that
/// replacement and quietly stops matching everything around it.
///
/// Three values in the scheme's own tonal shape, so the trio reads in either brightness:
///
/// * [warn] — the bar segment, the outline, the number on a plain surface.
/// * [warnContainer] — the pale fill behind a chip.
/// * [onWarnContainer] — what stays readable on top of that fill.
///
/// Pulled towards the orange end of amber rather than towards yellow: a pure yellow at 55° has
/// no dark step that stays yellow, and the light theme needs one that carries text.
/// `app_tones_test.dart` pins the band and the distance from both `primary` and `error`, so the
/// intent survives a re-export of the palette.
extension StockTone on ColorScheme {
  Color get warn => brightness == Brightness.dark
      ? const Color(0xfff0c176)
      : const Color(0xff8a5a00);

  Color get warnContainer => brightness == Brightness.dark
      ? const Color(0xff5c3f00)
      : const Color(0xffffdea8);

  Color get onWarnContainer => brightness == Brightness.dark
      ? const Color(0xffffdea8)
      : const Color(0xff4a3000);
}
