import 'dart:io';

import 'package:flutter_test/flutter_test.dart';

/// The mechanical guard on a release build being able to reach the network at all.
///
/// **This is the one permission the app cannot run without, and the one Flutter's template
/// leaves out of the manifest that ships.** `INTERNET` is declared in
/// `android/app/src/debug/AndroidManifest.xml` and its profile twin — both generated by the
/// Flutter tool so it can talk to the running app — and those are merged into debug and profile
/// builds only. The `main` manifest, which is the only one a release build sees, is left to the
/// developer.
///
/// So the failure has the worst possible shape: `flutter run` works, the emulator works, every
/// widget test works, and the first build that cannot open a socket is the signed APK handed to
/// somebody. Dio reports the blocked socket as a connection failure and the app renders it as
/// "no internet connection" — on a phone with working internet, pointed at a healthy server.
/// That is precisely what shipped, and what this test exists to stop shipping again.
///
/// A comment was tried first: the staff app carries one saying all of this, directly above its
/// `<uses-permission>` line. The port to this app copied neither the comment nor the line. A
/// comment cannot fail a build, so this reads the manifest instead.
///
/// Arrange - Act - Assert throughout.
void main() {
  final manifest = File('android/app/src/main/AndroidManifest.xml');

  test('the manifest a release build ships declares INTERNET', () {
    // Arrange
    final xml = manifest.readAsStringSync();

    // Act
    final declares = RegExp(
      r'<uses-permission\s+android:name\s*=\s*"android\.permission\.INTERNET"\s*/?>',
    ).hasMatch(xml);

    // Assert
    expect(
      declares,
      isTrue,
      reason:
          'android/app/src/main/AndroidManifest.xml is missing '
          '<uses-permission android:name="android.permission.INTERNET"/>. Without it a release '
          'build cannot open a socket, and every screen reports "no internet connection". The '
          'debug and profile manifests declare it for you, so nothing you run locally will show '
          'this.',
    );
  });
}
