<?php

declare(strict_types=1);

namespace App\Application\Api\V1\Controllers;

use App\Application\Api\V1\Requests\Customer\SetCustomerActivationRequest;
use App\Application\Api\V1\Requests\Customer\StoreCustomerRequest;
use App\Application\Api\V1\Requests\Customer\UpdateCustomerRequest;
use App\Application\Api\V1\Resources\CustomerResource;
use App\Application\Controller;
use App\Domain\Customer\CustomerService;
use App\Domain\Customer\DTOs\CustomerData;
use App\Domain\Customer\Models\Customer;
use App\Domain\Customer\Queries\CustomerFilters;
use App\Support\ResponseTrait;
use Illuminate\Http\JsonResponse;
use Illuminate\Http\Request;

/**
 * Customers
 *
 * Customers of the printing business and the shops they sell from.
 *
 * Each customer gets a permanent code of the form `C1`, `C2`, `C3` … derived from their id.
 * It is assigned by the server and cannot be sent or changed by a client.
 */
class CustomerController extends Controller
{
    use ResponseTrait;

    public function __construct(private readonly CustomerService $customers) {}

    /**
     * List customers
     *
     * Newest first. `search` matches the name, the code, or the phone number.
     */
    public function index(Request $request): JsonResponse
    {
        $filters = CustomerFilters::fromArray($request->only(['search', 'is_active']));
        $perPage = min(max((int) $request->integer('per_page', 15), 1), 100);

        return $this->successWithPagination(
            CustomerResource::collection($this->customers->paginate($filters, $perPage)),
        );
    }

    /**
     * Create a customer
     *
     * Shops may be supplied inline. The `code` is generated by the server.
     */
    public function store(StoreCustomerRequest $request): JsonResponse
    {
        $customer = $this->customers->create(CustomerData::fromArray($request->validated()));

        return $this->created(new CustomerResource($customer), 'تم إضافة العميل بنجاح');
    }

    /**
     * Get one customer
     */
    public function show(Customer $customer): JsonResponse
    {
        return $this->success(new CustomerResource($customer->load('shops')));
    }

    /**
     * Update a customer
     *
     * Sending `shops` replaces the whole set: entries with an `id` are updated, entries
     * without one are added, and any shop left out is removed. Omit `shops` entirely to
     * leave them untouched.
     */
    public function update(UpdateCustomerRequest $request, Customer $customer): JsonResponse
    {
        $updated = $this->customers->update($customer, CustomerData::fromArray($request->validated()));

        return $this->success(new CustomerResource($updated), 'تم تحديث بيانات العميل بنجاح');
    }

    /**
     * Activate or deactivate a customer
     *
     * Customers are never deleted — deactivating keeps their history intact.
     */
    public function setActivation(SetCustomerActivationRequest $request, Customer $customer): JsonResponse
    {
        $updated = $this->customers->setActive($customer, $request->boolean('is_active'));

        return $this->success(
            new CustomerResource($updated),
            $updated->is_active ? 'تم تنشيط العميل' : 'تم إلغاء تنشيط العميل',
        );
    }
}
